### ISSUE TITLE
Cannot find module 'sqlocal/drizzle' or its corresponding type declarations.ts(2307)

### ISSUE THREAD

**Issue by reslear** [DallasHoff/sqlocal#1]
<img width="955" alt="Screenshot 2023-08-06 at 17 44 27" src="https://github.com/DallasHoff/sqlocal/assets/12596485/ab9b1025-381b-4fb4-8181-aff97b615497">

maybe need to migrate https://github.com/egoist/tsup to better generate js mjs d.ts

**Comment by DallasHoff** [comment]
Hi there! It would be helpful if you could describe in more detail what issue you are having and provide some information about your environment's setup. In this case, the most relevant information would probably be your package.json file and your TypeScript configuration.

Ideally, you could provide a minimal reproduction. As an example, I just put together a minimal "hello world" app for using SQLocal with Drizzle here: https://github.com/DallasHoff/sqlocal-drizzle-hello-world
Check that repo out and see if it helps point you to your issue. If not, you might make something similar that demonstrates your problem so that I can investigate what fix would be needed.

**Comment by proof-llc** [comment]
I have the same issue with `sqlocal/kysely`:
`Cannot find module 'sqlocal/kysely' or its corresponding type declarations`
<img width="1101" alt="Screenshot 2023-08-08 at 4 44 52 PM" src="https://github.com/DallasHoff/sqlocal/assets/112896565/35da9721-8b5e-4868-b044-ab3641c01eeb">

**Comment by proof-llc** [comment]
i don't have the problem with the hello-world project. it's an issue with `tsconfig.json`. you're using "moduleResolution": "bundler", instead of "node".

**Comment by DallasHoff** [comment]
Ah, I see. Can I ask why you use "moduleResolution": "node"? The [TypeScript docs](https://www.typescriptlang.org/tsconfig#moduleResolution) say it's for "Node.js versions older than v10, which only support CommonJS require. You probably won’t need to use node10 in modern code." SQLocal is for the browser, not Node, and as far as I know, "moduleResolution": "node" does not support sub-module resolution for ES modules. Is there a requirement you have to use "node"?

@reslear Are you also using "moduleResolution": "node"?

**Comment by proof-llc** [comment]
A lot of libs/tools out there unfortunately haven't had the chance to adapt to the new "bundler". I am using svelte-kit and it appears they need more time: https://github.com/sveltejs/kit/issues/9007 . It would help if we can have compatibility until end of the year.

When I make the change in tsconfig to "bundler". I no longer get syntax error, but during build, i get:
```
Error [ERR_MODULE_NOT_FOUND]: Cannot find module '.../node_modules/.pnpm/sqlocal@0.5.1/node_modules/sqlocal/dist/kysely/client' imported from .../node_modules/.pnpm/sqlocal@0.5.1/node_modules/sqlocal/dist/kysely/index.js
```

**Comment by proof-llc** [comment]
When I make the change in tsconfig to "bundler". I no longer get syntax error; now I get during runtime:
```
Error [ERR_MODULE_NOT_FOUND]: Cannot find module '.../node_modules/.pnpm/sqlocal@0.5.1/node_modules/sqlocal/dist/kysely/client' imported from .../node_modules/.pnpm/sqlocal@0.5.1/node_modules/sqlocal/dist/kysely/index.js
```

I created a simple project to figure the issue - can you please see what I might be missing here: https://github.com/proof-llc/sqlocal-kysely-hello-world
This https://github.com/sveltejs/kit/issues/9007 may be relevant (not sure)

**Comment by DallasHoff** [comment]
@reslear Could you tell me what you have the "moduleResolution" option set to in your tsconfig.json?

**Comment by reslear** [comment]
@DallasHoff `bundler`

**Comment by DallasHoff** [comment]
And you are still having the module resolution issue with it set to "bundler"?

**Comment by reslear** [comment]
As I recalled it was then, I can't verify it now.

**Comment by DallasHoff** [comment]
What do you mean by you can't verify it? I just need to know if you get the module resolution error that you originally reported while the "moduleResolution" option is set to "bundler". You shouldn't. That error should only happen if you use a legacy option like "node".

**Comment by DallasHoff** [comment]
Closing. This issue can be fixed by making sure your TypeScript configuration's `moduleResolution` option is set to `bundler` or `nodenext`. Legacy values for `moduleResolution` like `node` do not support submodule resolution for ES modules.

**Comment by adampash** [comment]
Obviously this is completely up to you to decide, but forcing the `moduleResolution` change is going to make adoption difficult for a lot of projects that don't use these resolution options for various interop reasons unique to the projects. (If I change my module resolution, a lot of existing packages I'm using won't work.) This is the first time I've run into a dependency where this is a requirement.

**Comment by DallasHoff** [comment]
Of course it would be ideal if the library worked with all possible `moduleResolution` settings, but I have not been able to get the library working with `moduleResolution` set to `node`.  SQLocal is only useable in the browser, not Node.js, and it relies on fairly modern features like the Origin Private File System API and ESM web workers, so supporting projects built around legacy versions of Node.js is probably not feasible. Though, if you have any specific ideas for how that support can be improved, please do suggest them here or open a PR.

**Comment by adampash** [comment]
Yep, understood. I think an _okay_ workaround, if someone can't use a more modern module resolution value, is to add something like the following to the `compilerOptions.paths` in their tsconfig:

```json
    "paths": {
      "sqlocal/*": ["../node_modules/sqlocal/dist/*"]
    }
```

Where the path to the node module is relative to the `baseUrl` in their tsconfig.
