### ISSUE TITLE
sqlocal easy connect/disconnect

### ISSUE THREAD

**Issue by MigFerreira** [DallasHoff/sqlocal#2]
I have a use case where I have to connect and disconnect on demand from databases.
Because of this I have created a wrapper to manage this, as a singleton. 

I think it could be useful if the sqlocal client wouldn't actually connect to database on construction if fileName param was empty, and add the ability to connect on demand.

Any thoughts?

**Comment by DallasHoff** [comment]
I'd like to understand your use case a bit more. Could you describe it in more detail? Why do you need to frequently connect to and disconnect from the same database file?

**Comment by MigFerreira** [comment]
I have a syncable (cloud storage) database per user protected. Basically each db will be <user_id>.db
Only thing remaining is check how I can add encryption.

**Comment by AlexErrant** [comment]
Off topic - if you're looking for a syncable sqlite that works in the browser, why note use https://github.com/vlcn-io/cr-sqlite?

I currently have cr-sqlite syncing over PeerJS, and very recently added public/private key authentication to my PeerJS connections https://github.com/AlexErrant/Pentive/commit/3bf14c11254b809c7987fd1859d328b3e567fc22

**Comment by DallasHoff** [comment]
That's still not much to go on. I ask for more details so I can understand your use case and keep it in mind to potentially better support it as I work on the library. However, what you have described so far does not seem to necessitate adding an extra step to initialize the SQLocal client. As it is set up now, the SQLocal class essentially _is_ your connection; you initialize it to connect, and call `SQLocal.destroy()` to disconnect. To make a new connection, you initialize another instance of SQLocal. I feel like this keeps things simple, but please let me know if there is something that you feel that I am not accounting for.

**Comment by MigFerreira** [comment]
Fair enough, what you described is basically what Im doing, I built a singleton wrapper with connect and disconnect that manages SQLocal instance.
Understandable you want to keep sqlocal clean and simple.
