### ISSUE TITLE
Sqlocal with pglite

### ISSUE THREAD

**Issue by MirjamElad** [DallasHoff/sqlocal#20]
Hello,
Would you consider making sqlocal work with PgLite?
https://github.com/electric-sql/pglite
It's just like sqlite-wasm but it is rather an implementation of PosgreSQL made by the people in Electric-SQL and Neon

**Comment by DallasHoff** [comment]
The main goals of SQLocal are to simplify the usage of SQLite WASM by abstracting away all of the boilerplate code you need to run it in a web worker and to provide a straightforward API and integrations with type-safe query builders. I've been watching the PGLite project, and it looks they already have an API with similar abstractions, and they plan to add integrations with query builders like Drizzle soon. Given this, there's not really anything we can offer by building an SQLocal integration for PGLite.
