### ISSUE TITLE
How do you debug or visualize the database?

### ISSUE THREAD

**Issue by NLegendre** [DallasHoff/sqlocal#23]
Hello,
I was wondering if there is a solution to "visualize" and debug the database tables (and the content)?
Maybe something like PhpMyAdmin or like the browser inspector for indexedDB.
Thank you for your help!

**Comment by NLegendre** [comment]
I found a solution, I don't know if it's the more effective:
- download and install this extension: https://chromewebstore.google.com/detail/acndjpgkpaclldomagafnognkcgjignd?hl=fr
- it give you the possibility to download the .sqlite3 file
- then use a webapp or an app to display the content of the file. Here are some apps I found : (https://inloop.github.io/sqlite-viewer/, https://sqliteviewer.app/, https://sqlitebrowser.org/)

Let me know if you have a lighter solution :)

**Comment by DallasHoff** [comment]
Yeah, that's exactly what I would have recommended.
