### ISSUE TITLE
Passing a variable to `sql` function

### ISSUE THREAD

**Issue by pycanis** [DallasHoff/sqlocal#33]
Hello, first of all, thank you for this library. If the following is going to work, it's going to be a game changer for my apps.

I need to pass a variable (of raw sql string) to the `sql` function. The only way I found the library allowed me to use was sql\`${rawSql}\`. Unfortunately, this results in `SQLite3Error: SQLITE_ERROR: sqlite3 result code 1: near "?": syntax error`. 

Could we also have an option to use `sql(rawSql)` or something similar?

**Comment by DallasHoff** [comment]
Yeah, that's easy enough. I can include a tweak that allows `sql(rawSql)` in the next update.

**Comment by pycanis** [comment]
> Yeah, that's easy enough. I can include a tweak that allows `sql(rawSql)` in the next update.

That would be perfect, thank you!

**Comment by DallasHoff** [comment]
Added in the new version [0.10.2](https://github.com/DallasHoff/sqlocal/releases/tag/v0.10.2)
