### ISSUE TITLE
How to make "private dbs" for individual users?

### ISSUE THREAD

**Issue by morgs32** [DallasHoff/sqlocal#35]
It's mentioned in the README but I don't see how to do it or how it works. I'll keep trying but maybe it's fairly easy to explain?

**Comment by DallasHoff** [comment]
That line just refers to the fact that SQLocal databases live on the user's device, rather than being centralized on a server, so each user's data is made private and secure by their own device without sacrificing the data processing power that traditionally server-based solutions provide. 

Does that make sense? Was there a different feature you were looking for or expecting when you read that line?

**Comment by morgs32** [comment]
Ahh, that makes sense. Thanks. I was hoping there might be a way to encrypt the sqlite db somehow, so that you could have multiple "tenants" on the one device. I also am not totally sure if a B2B app that's all GDPR and SOC 1/2 compliant needs that data to be encrypted on the device... will keep looking! Wouldn't mind at all if you closed this or wanted to move this to a discussion?

**Comment by morgs32** [comment]
I think I'm starting to understand that the OPFS is a) not visible to users and b) only accessible by web workers that c) can't be inspected or debugged or tampered with on the client. So if I use your library to create different sqlite dbs in different files then they should be pretty secure.

**Comment by DallasHoff** [comment]
Files in the OPFS do not appear as regular files outside the browser, so users would not be able to find them by browsing their file system. However, as with any files used in a web page, a person with the knowledge to use the web inspector can find any code your web page sends to the browser as well as any files stored in the OPFS. Files in the OPFS are private in the sense that they can only be accessed and changed by the website (origin) that created them. The site can manipulate its own OPFS files from the main thread or a worker as long as the site is in a [secure context](https://developer.mozilla.org/en-US/docs/Web/Security/Secure_Contexts).

You should not need to encrypt SQLite files in the browser. They are local and partitioned by user just like other browser files and settings. SQLite does offer a product that allows it to work with encrypted databases, but even they give [many reasons](https://sqlite.org/wasm/doc/trunk/see.md) why such a solution is pretty pointless for browser-based apps.
