### ISSUE TITLE
Differences from the official wrapper

### ISSUE THREAD

**Issue by PorcoRosso85** [DallasHoff/sqlocal#42]
Hi

The official has this wrapper, can you tell me the difference?
https://github.com/sqlite/sqlite-wasm

**Comment by DallasHoff** [comment]
Hi there. The package you linked is what SQLocal wraps. sqlite-wasm provides the WebAssembly build of SQLite3 and low-level bindings. SQLocal builds on that with higher-level abstractions for interacting with sqlite-wasm.
