### ISSUE TITLE
Cross-Origin Isolation blocks images

### ISSUE THREAD

**Issue by Bobakanoosh** [DallasHoff/sqlocal#44]
Upon adding the recommended Vite plugin for Cross-Origin Isolation:
```ts
		plugins: [
			{
				name: "configure-response-headers",
				configureServer: (server) => {
					server.middlewares.use((_req, res, next) => {
						res.setHeader("Cross-Origin-Embedder-Policy", "require-corp");
						res.setHeader("Cross-Origin-Opener-Policy", "same-origin");
						next();
					});
				},
			},
		],
```

I get errors like in the browser console.
```ts
GET <image_url> net::ERR_BLOCKED_BY_RESPONSE.NotSameOriginAfterDefaultedToSameOriginByCoep 200 (OK)
```
I don't know enough about cross origin to fix this - I tried adjusting the middleware to not set headers `if(_req.url.includes('webp'))`, but strangely the middleware isn't called for the image urls?

**Comment by DallasHoff** [comment]
It sounds like your images are being loaded from a different origin. In that case, you need to add the `crossorigin` attribute to your `img` elements to opt-in to a cross-origin request while cross-origin isolation is enabled. 

```html
<img src="https://example.com/image.webp" crossorigin>
```

**Comment by Bobakanoosh** [comment]
Just needed to adjust some of the headers on the assets being served, but worked!! Thanks so much
