### ISSUE TITLE
Migrations during development / delete database file

### ISSUE THREAD

**Issue by Bobakanoosh** [DallasHoff/sqlocal#50]
I haven't released my app yet, so building a migration each time I change a table doesn't make sense. However, because duplicate migrations cant be run, this means I have to change my database name each time I have a migration change.

Is there a way around this?

**Comment by DallasHoff** [comment]
For development, I'd recommend using the [OPFS Explorer extension](https://chromewebstore.google.com/detail/opfs-explorer/acndjpgkpaclldomagafnognkcgjignd). It lets you see a list of files in the OPFS from your dev tools and delete them as needed.
