### ISSUE TITLE
Possibility of using SQLite extensions?

### ISSUE THREAD

**Issue by ashokgelal** [DallasHoff/sqlocal#56]
Is it possible to load SQLite extensions with SQLocal? If yes, is there any docs that I could read to get started? Or maybe an example?

**Comment by DallasHoff** [comment]
`sqlite-wasm` does not support dynamically loading extensions ([see their docs](https://sqlite.org/wasm/doc/trunk/building.md#extra-init)). The extensions built into SQLite by default (such as full-text search, JSON, and sessions) are available in SQLocal, but to add custom ones, you will have to recompile `sqlite-wasm` yourself.
