### ISSUE TITLE
Replace Sqlite3 with Libsql

### ISSUE THREAD

**Issue by ansarizafar** [DallasHoff/sqlocal#6]
Libsql is a fork of SQlite3 and has more features like [ALTER TABLE extension for modifying column types and constraints](https://github.com/libsql/libsql/blob/main/doc/libsql_extensions.md#altering-columns) 

I recommend replacing Sqlite3 with Liqsql https://github.com/tursodatabase/libsql

**Comment by DallasHoff** [comment]
The point of SQLocal is to run the database in the browser. libSQL does not have a build that runs in the browser.

**Comment by terpimost** [comment]
would it be possible to support https://github.com/tursodatabase/libsql-client-ts/tree/main/packages/libsql-client-wasm/examples/browser ?
